### ISSUE TITLE
Uncaught Error: Call to undefined method Magento\Payment\Model\Method\Logger::error in BasePayment

### ISSUE THREAD

**Issue by unicoder88** [Ecomatic/Collector-Checkout-Magento-2#19]
Hi!

We're facing server 500 error when making partial invoice.

```
2019/01/08 15:19:47 [error] 16558#16558: *9960581 FastCGI sent in stderr: "PHP message: PHP Fatal error: 
Uncaught Error: Call to undefined method Magento\Payment\Model\Method\Logger::error() in /var/www/leba.dev.convert.no/www/app/code/Collector/Iframe/Model/Payment/BasePayment.php:299
Stack trace:
#0 /var/www/leba.dev.convert.no/www/vendor/magento/module-sales/Model/Order/Payment/Operations/CaptureOperation.php(82): Collector\Iframe\Model\Payment\BasePayment->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), '599')
#1 /var/www/leba.dev.convert.no/www/vendor/magento/module-sales/Model/Order/Payment/Processor.php(85): Magento\Sales\Model\Order\Payment\Operations\CaptureOperation->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice))
#2 /var/www/leba.dev.convert.no/www/vendor/magento/module-sales/Model/Order/Payment.php(467): Magento\Sales\Model\Order\Payment\Processor->capture(Object(Magento\Sales\Model\Order\Payment\Interceptor), Object(Magento\Sales\Model\Order\Invoice))
#3 /var/www/leba.dev.convert.no/www/vendor" while reading response header from upstream, client: 146.185.165.54, server: leba.dev.convert.no, request: "POST /admin/sales/order_invoice/save/order_id/135/key/9b88f22df0d2eeed70ede92703630c060d098ab826894b017033456e9f1feabd/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm-leba.sock:", host: "leba.dev.convert.no", referrer: "http://leba.dev.convert.no/admin/sales/order_invoice/new/order_id/135/key/1e121fe16ed97cc8c9a7c6471d30c5c45ae34ab4e4a98bdb3a82682838fd33f8/"
```

I will report partial invoice issue separately, but point here is that logger instance is of not expected type and fails in [BasePayment](https://github.com/Ecomatic/Collector-Checkout-Magento-2/blob/master/Collector/Iframe/Model/Payment/BasePayment.php). This is because we first [assign Collector logger](https://github.com/Ecomatic/Collector-Checkout-Magento-2/blob/master/Collector/Iframe/Model/Payment/BasePayment.php#L94), but then [parent reassigns](https://github.com/magento/magento2/blob/2.2-develop/app/code/Magento/Payment/Model/Method/AbstractMethod.php#L267) `logger` property to another class.

Regards,
Roman

**Comment by henrik-lofstrom** [comment]
solved

**Comment by unicoder88** [comment]
Thanks :)
